services:
  backend:
    build: .
    command: npm run start
    env_file:
      - .env
    environment:
      NODE_ENV: production
      MONOLITHIC_MODE: "true"
      PORT: 4000
      MONOLITH_PORT: 4000
    ports:
      - "${PORT:-4000}:4000"
